# Generated by Django 2.1.7 on 2019-03-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190326_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientName',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientType',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceID',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='testsequence',
            name='SequenceID',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(max_length=25),
        ),
    ]
